### ISSUE TITLE
google colab: fine-tuning spanbert on dataset

### ISSUE THREAD

**Issue by ifmaq1** [s3vqa/s3vqa.github.io#1]
considering this line in colab notebook

"We use SpanBERT as a QA system (which taken question and context as input and outputs a span from the context as the answer for the question).
For this work, we have fine-tuned SpanBERT on OKVQAS3."

Do I need to train this dataset myself on OKVQAS3? As it throws an error attached below
![error_colab](https://user-images.githubusercontent.com/67015296/117570519-da367980-b0e3-11eb-823c-0e7f99ee4689.png)

**Comment by s3vqa** [comment]
Yes, you'll have to finetune SpanBERT on OKVQA_S3 first.
